[package]
name = "DreamLauncher"
authors = ["Frogdream Studios"]
description = "A powerful and lightweight Minecraft launcher that will be perfect for every player."
license = "LGPL-3.0-only"
version = "1.0.0-beta.1"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.0-alpha.3", features = ["desktop"] }
dioxus-router = "0.7.0-alpha.3"
dioxus-desktop = { version = "0.7.0-alpha.3", default-features = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1.47.0", features = ["full"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
reqwest = { version = "0.12.22", features = ["json", "stream", "rustls-tls"] }
futures-util = "0.3.31"
zip = "4.3.0"
flate2 = "1.1.2"
tar = "0.4.44"
clap = { version = "4.4.42", features = ["derive"] }
dialoguer = "0.11.0"
console = "0.16.0"
sha1 = "0.11.0-rc.0"
dirs = "6.0.0"
hex = "0.4.3"
which = "8.0.0"
tracing = "0.1.41"
anyhow = "1.0.98"
image = "0.25.6"
tao = "0.34.0"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
