[package]
name = "DreamLauncher"
authors = ["Frogdream Studios"]
description = "A powerful and lightweight Minecraft launcher that will be perfect for every player."
repository = "https://github.com/FrogdreamStudios/launcher"
keywords = ["minecraft", "launcher", "java", "gaming", "cross-platform"]
categories = ["games"]
license = "LGPL-3.0-only"
version = "1.0.0-beta.1"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.0-rc.0", features = ["desktop"] }
dioxus-router = "0.7.0-rc.0"
dioxus-desktop = { version = "0.7.0-rc.0", default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = [
    "rt-multi-thread",
    "fs",
    "process",
    "time",
    "sync",
    "macros",
] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
reqwest = { version = "0.12.23", features = [
    "json",
    "stream",
    "native-tls",
], default-features = false }
futures-util = { version = "0.3.31", default-features = false, features = [
    "std",
] }
flate2 = { version = "1.1.2", default-features = false, features = [
    "rust_backend",
] }
tar = { version = "0.4.44", default-features = false }
sha1 = "0.11.0-rc.0"
dirs = "6.0.0"
hex = "0.4.3"
which = "8.0.0"
tracing = "0.1.41"
anyhow = "1.0.99"
image = { version = "0.25.6", default-features = false, features = ["png"] }
tao = "0.34.0"
zip = { version = "4.3.0", default-features = false, features = ["deflate"] }

[build-dependencies]
winres = "0.1.12"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]

[profile.dev]
incremental = true

[lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
style = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
large_stack_arrays = "deny"
large_types_passed_by_value = "deny"
box_collection = "deny"
vec_box = "deny"
rc_buffer = "deny"
rc_mutex = "deny"
redundant_clone = "deny"
unnecessary_to_owned = "deny"
unnecessary_box_returns = "deny"
needless_collect = "deny"
needless_borrow = "deny"
needless_pass_by_value = "deny"
implicit_clone = "deny"
clone_on_copy = "deny"
