[package]
name = "DreamLauncher"
authors = ["Frogdream Studios"]
description = "A powerful and lightweight Minecraft launcher that will be perfect for every player."
repository = "https://github.com/FrogdreamStudios/launcher"
keywords = ["minecraft", "launcher", "java", "gaming", "cross-platform"]
categories = ["games"]
license = "LGPL-3.0-only"
version = "1.0.0-beta.1"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.0-rc.0", features = ["desktop"] }
dioxus-router = "0.7.0-rc.0"
dioxus-desktop = { version = "0.7.0-rc.0", default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = [
    "rt-multi-thread",
    "fs",
    "process",
    "time",
    "sync",
    "macros",
], default-features = false }
reqwest = { version = "0.12.23", features = [
    "json",
    "stream",
    "native-tls",
], default-features = false }

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]

minimal = []

[profile.dev]
incremental = true
debug = 1
opt-level = 1

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
overflow-checks = false
debug-assertions = false
rpath = false
incremental = false
debug = false
split-debuginfo = "off"

[profile.release.package."*"]
opt-level = "z"

[lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
style = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
large_stack_arrays = "deny"
large_types_passed_by_value = "deny"
box_collection = "deny"
vec_box = "deny"
rc_buffer = "deny"
rc_mutex = "deny"
redundant_clone = "deny"
unnecessary_to_owned = "deny"
unnecessary_box_returns = "deny"
needless_collect = "deny"
needless_borrow = "deny"
needless_pass_by_value = "deny"
implicit_clone = "deny"
clone_on_copy = "deny"
