[package]
name = "DreamLauncher"
authors = ["Frogdream Studios <"]
description = "A powerful and lightweight Minecraft launcher that will be perfect for every player."
license = "LGPL-3.0-only"
version = "1.0.0-beta.1"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.0-alpha.3", features = ["desktop"] }
dioxus-router = "0.7.0-alpha.3"
dioxus-desktop = { version = "0.7.0-alpha.3", default-features = true }
tokio = { version = "1.47.0", features = ["full"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]