[application]
name = "Dream Launcher"
default_platform = "desktop"

[web.app]
title = "Dream Launcher"

[bundle]
identifier = "com.frogdream.dreamlauncher"
publisher = "Frogdream Studios"
icon = ["assets/icons/app_icon.icns"]
resources = ["assets/**/*"]
short_description = "A powerful and lightweight Minecraft launcher"
long_description = "A powerful and lightweight Minecraft launcher that will be perfect for every player"
# category = "Game"

[bundle.linux]
app_name = "DreamLauncher"
short_description = "A powerful and lightweight Minecraft launcher"
long_description = "A powerful and lightweight Minecraft launcher that will be perfect for every player"

[bundle.macos]
app_name = "Dream Launcher"
files = {}
hardened_runtime = false

[bundle.windows]
webview2_install_mode = "embedbootstrapper"
webview2_user_data_folder = ".dream-launcher"
console_subsystem = false
