name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  windows:
    name: Windows
    runs-on: windows-2025
    strategy:
      matrix:
        format: [ x64, arm64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup icon
        run: |
          mkdir -p icons
          cp assets/icons/app_icon.ico icons/icon.ico
        shell: bash

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Setup Python libs
        if: matrix.format == 'arm64'
        shell: pwsh
        run: |
          $pythonRoot = (python -c "import sys; print(sys.base_prefix)")
          $libPath = Join-Path $pythonRoot "libs"
          echo "LIB=$libPath;$env:LIB" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: win-${{ matrix.format }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: win-${{ matrix.format }}-

      - name: Install cargo-binstall
        shell: pwsh
        run: |
          $BinDir = "$env:USERPROFILE\.cargo\bin"
          if (!(Test-Path $BinDir)) { New-Item -ItemType Directory -Path $BinDir | Out-Null }
          iwr https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-pc-windows-msvc.zip -OutFile binstall.zip
          Expand-Archive binstall.zip -DestinationPath $BinDir -Force
          echo "$BinDir" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Install Rust
        if: matrix.format == 'arm64'
        run: |
          rustup update stable
          rustup target add aarch64-pc-windows-msvc
          rustup component add rust-src

      - name: Install dx
        shell: pwsh
        run: cargo binstall dioxus-cli --version 0.7.0-rc.0 -y

      - name: Build
        run: |
            dx bundle --release --platform desktop
        shell: bash

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dreamlauncher-windows-${{ matrix.format }}
          path: target/dx/DreamLauncher/bundle/windows/*.exe

  linux:
    name: Linux
    runs-on: ubuntu-24.04
    continue-on-error: true
    strategy:
      matrix:
        format: [ deb, rpm ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Install cargo-binstall
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install dx
        run: cargo binstall dioxus-cli --version 0.7.0-rc.0 -y

      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libgtk-3-dev libglib2.0-dev libsoup-3.0-dev libssl-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev libxdo-dev pkg-config build-essential curl xdotool fuse libfuse2 desktop-file-utils appstream file
          version: 1

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: linux-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.format }}-${{ github.run_id }}
          restore-keys: linux-

      - name: Install Rust
        run: rustup update stable

      - name: Build
        run: |
          export NO_STRIP=true
          dx bundle --verbose --trace --release --platform desktop --package-types ${{ matrix.format }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dreamlauncher-linux-${{ matrix.format }}
          path: target/dx/DreamLauncher/bundle/linux/bundle/${{ matrix.format }}/*.${{ matrix.format }}

  macos-app:
    name: macOS
    runs-on: macos-15
    strategy:
      matrix:
        format: [ dmg ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/dx
            ~/.cargo/bin/cargo-binstall
          key: macos-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: macos-
      - name: Install cargo-binstall
        run: |
          if [ ! -f ~/.cargo/bin/cargo-binstall ]; then
            curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          fi
      - name: Install dx
        run: |
          if [ ! -f ~/.cargo/bin/dx ]; then
            cargo binstall dioxus-cli --version 0.7.0-rc.0 -y || cargo install dioxus-cli --version 0.7.0-rc.0
          fi

      - name: Build
        run: |
          dx bundle --release --platform desktop --package-types dmg
      
      - name: Embed Python Framework
        run: |
          # Find the DMG file
          DMG_PATH=$(find target/dx/DreamLauncher/bundle/macos/bundle/dmg -name "*.dmg" | head -1)
          if [ -n "$DMG_PATH" ]; then
            # Mount DMG and copy app to temporary location
            hdiutil attach "$DMG_PATH" -mountpoint /tmp/dmg_mount
            cp -R "/tmp/dmg_mount/DreamLauncher.app" "/tmp/DreamLauncher_modified.app"
            hdiutil detach /tmp/dmg_mount
            
            APP_PATH="/tmp/DreamLauncher_modified.app"
            
            # Create Frameworks directory
            mkdir -p "$APP_PATH/Contents/Frameworks"
            
            # Copy only the Python dynamic library
            PYTHON_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1-2)
            FRAMEWORK_PATH="$APP_PATH/Contents/Frameworks/Python.framework/Versions/$PYTHON_VERSION"
            mkdir -p "$FRAMEWORK_PATH"
            
            if [ -d "/Library/Frameworks/Python.framework" ]; then
              # Copy only the Python dynamic library
              cp "/Library/Frameworks/Python.framework/Versions/$PYTHON_VERSION/Python" "$FRAMEWORK_PATH/"
            elif [ -d "$RUNNER_TOOL_CACHE/Python" ]; then
              # GitHub Actions Python location - find the dynamic library
              PYTHON_DIR=$(find "$RUNNER_TOOL_CACHE/Python" -name "$PYTHON_VERSION*" | head -1)
              if [ -n "$PYTHON_DIR" ]; then
                # Look for the Python dynamic library
                find "$PYTHON_DIR" -name "libpython$PYTHON_VERSION*.dylib" -exec cp {} "$FRAMEWORK_PATH/Python" \; 2>/dev/null || true
                # If not found, try alternative locations
                if [ ! -f "$FRAMEWORK_PATH/Python" ]; then
                  find "$PYTHON_DIR" -name "Python" -type f -exec cp {} "$FRAMEWORK_PATH/" \; 2>/dev/null || true
                fi
              fi
            else
              # Use the Python from GitHub Actions
              PYTHON_ROOT=$(python -c "import sys; print(sys.base_prefix)")
              mkdir -p "$FRAMEWORK_PATH"
              # Copy only the dynamic library, not everything
              find "$PYTHON_ROOT" -name "libpython$PYTHON_VERSION*.dylib" -exec cp {} "$FRAMEWORK_PATH/Python" \; 2>/dev/null || true
              if [ ! -f "$FRAMEWORK_PATH/Python" ]; then
                cp "$PYTHON_ROOT/bin/python$PYTHON_VERSION" "$FRAMEWORK_PATH/Python" 2>/dev/null || true
              fi
              ln -sf "$PYTHON_VERSION" "$APP_PATH/Contents/Frameworks/Python.framework/Versions/Current"
              ln -sf "Versions/Current/Python" "$APP_PATH/Contents/Frameworks/Python.framework/Python"
            fi
            
            # Sign the Python library with ad-hoc signature
            if [ -f "$FRAMEWORK_PATH/Python" ]; then
              # Check if already signed, if so remove signature first
              if codesign -dv "$FRAMEWORK_PATH/Python" 2>&1 | grep -q "Signature="; then
                echo "Removing existing signature from Python library"
                codesign --remove-signature "$FRAMEWORK_PATH/Python"
              fi
              codesign -s - "$FRAMEWORK_PATH/Python"
            fi
            
            # Copy icon file to Resources
            cp "assets/icons/app_icon.icns" "$APP_PATH/Contents/Resources/icon.icns"
            
            # Update Info.plist to fix app name and icon
            /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName 'Dream Launcher'" "$APP_PATH/Contents/Info.plist"
            /usr/libexec/PlistBuddy -c "Set :CFBundleName 'Dream Launcher'" "$APP_PATH/Contents/Info.plist"
            /usr/libexec/PlistBuddy -c "Set :CFBundleIconFile icon.icns" "$APP_PATH/Contents/Info.plist"
            
            # Update install names
            EXECUTABLE="$APP_PATH/Contents/MacOS/DreamLauncher"
            install_name_tool -change "/Library/Frameworks/Python.framework/Versions/3.13/Python" "@executable_path/../Frameworks/Python.framework/Versions/3.13/Python" "$EXECUTABLE"
            
            # Rename the app to "Dream Launcher.app"
            mv "$APP_PATH" "/tmp/Dream Launcher.app"
            
            # Recreate DMG with embedded Python
            rm "$DMG_PATH"
            hdiutil create -volname "Dream Launcher" -srcfolder "/tmp/Dream Launcher.app" -ov -format UDZO "$DMG_PATH"
            
            # Clean up temporary app
            rm -rf "/tmp/Dream Launcher.app"
          fi
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dreamlauncher-macos-${{ matrix.format }}
          path: target/dx/DreamLauncher/bundle/macos/bundle/dmg/*.dmg
