# Rust workflow to build and package the launcher for Windows, macOS, and Linux.

name: Rust CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Deps (Windows)
        run: choco install upx

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: windows-allcache-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: windows-allcache-

      - name: Build
        run: cargo build --release --locked --features "desktop"

      - name: Compress with UPX (Windows)
        run: |
          upx --best --lzma target/release/DreamLauncher.exe

      - name: Install NSIS (Windows)
        run: |
          choco install nsis -y

      - name: Create Windows Installer
        run: |
          mkdir dist
          powershell -ExecutionPolicy Bypass -File scripts/windows/build_installer.ps1 -Version "${{ github.ref_name || 'dev' }}"

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: DreamLauncher-Windows
          path: |
            dist/Dream Launcher Setup.exe

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Deps (Linux)
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libgtk-3-dev libglib2.0-dev libsoup-3.0-dev libssl-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev libxdo-dev pkg-config build-essential curl xdotool upx-ucl libfuse2
          version: 1

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: linux-allcache-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: linux-allcache-

      - name: Build
        run: cargo build --release --locked --features "desktop"

      - name: Compress with UPX (Linux)
        run: |
          upx --best --lzma target/release/DreamLauncher

      - name: Install AppImage dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y file
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool

      - name: Create AppImage (Linux)
        run: |
          chmod +x scripts/linux/appimage.sh
          ./scripts/linux/appimage.sh

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: DreamLauncher-Linux-AppImage
          path: |
            *.AppImage

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Deps (macOS)
        run: brew install create-dmg upx

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: macos-allcache-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: macos-allcache-

      - name: Build
        run: cargo build --release --locked --features "desktop"

      - name: Compress with UPX (macOS)
        run: |
          chmod +x scripts/macos/compress.sh
          ./scripts/macos/compress.sh "target/release/DreamLauncher"

      - name: Package for macOS
        shell: bash
        run: |
          set -e
          mkdir -p dist
          chmod +x scripts/macos/bundle.sh
          ./scripts/macos/bundle.sh

          chmod +x scripts/macos/clean.sh
          ./scripts/macos/clean.sh "target/release/Dream Launcher.app"

          chmod +x scripts/macos/sign.sh
          ./scripts/macos/sign.sh "target/release/Dream Launcher.app"

          chmod +x scripts/macos/dmg.sh
          ./scripts/macos/dmg.sh
          if [[ -f "Dream Launcher.dmg" ]]; then
            mv "Dream Launcher.dmg" "dist/Dream Launcher.dmg"
            echo "DMG created successfully"
          else
            echo "No DMG file found"
            exit 1
          fi

          echo "macOS packaging completed"

      - name: Upload macOS
        uses: actions/upload-artifact@v4
        with:
          name: DreamLauncher-macOS
          path: |
            dist/Dream Launcher.dmg
